image: python:3.11

stages:
  - test


variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

test_job:
  stage: test
  before_script:
    - python --version ; pip --version
    - pip install -r requirements.txt
  
  script:
    - python -m pytest -s -v ./tests

generer-pdf:
  stage: build
  image: 
    name: minlag/mermaid-cli:latest
    entrypoint: [""]
  
  rules:
    - changes:
        - docs/classDiagram.mmd
    - when: manual
      allow_failure: true
  
  script:
    - mmdc -i ./docs/classDiagram.mmd -o ./docs/classDiagram.pdf
  
  artifacts:
    paths:
      - docs/classDiagram.pdf
    expire_in: 1 week